/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package businessapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

import javax.swing.JOptionPane;

/**
 *
 * @author AFF COMPUTERS
 */
public class BusinessGUI extends javax.swing.JFrame {
    ArrayList <Business> elist = new ArrayList<>();
    private final guiMain main;
    File f;
    int count=1;
    String busFile ="BusList1.dat";

    
    /**
     * Creates new form BusinessGUI
     */
    public BusinessGUI(guiMain main) {
        this.main = main;
        getContentPane().setBackground(new java.awt.Color(173, 216, 230));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        objectTA = new javax.swing.JTextArea();
        nameLBL = new javax.swing.JLabel();
        revLBL = new javax.swing.JLabel();
        addBTN = new javax.swing.JButton();
        delBTN = new javax.swing.JButton();
        saveBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        resRBTN = new javax.swing.JRadioButton();
        texRBTN = new javax.swing.JRadioButton();
        manRBTN = new javax.swing.JRadioButton();
        openBTN = new javax.swing.JButton();
        nameTF = new javax.swing.JTextField();
        revTF = new javax.swing.JTextField();
        displayBTN = new javax.swing.JButton();
        searchBTN = new javax.swing.JButton();
        unitsTF = new javax.swing.JTextField();
        disTF = new javax.swing.JTextField();
        unitsLBL = new javax.swing.JLabel();
        disLBL = new javax.swing.JLabel();
        compTF = new javax.swing.JTextField();
        name5LBL = new javax.swing.JLabel();
        computeBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        imgLBL = new javax.swing.JLabel();
        esgLBL = new javax.swing.JLabel();
        costLBL = new javax.swing.JLabel();
        plasticLBL = new javax.swing.JLabel();
        newfBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        objectTA.setColumns(20);
        objectTA.setRows(5);
        jScrollPane1.setViewportView(objectTA);

        nameLBL.setText("Name");

        revLBL.setText("Revenue");

        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        delBTN.setText("Delete");
        delBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBTNActionPerformed(evt);
            }
        });

        saveBTN.setText("Save");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        resRBTN.setBackground(new java.awt.Color(173, 216, 230));
        resRBTN.setText("Restaurant");
        resRBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resRBTNActionPerformed(evt);
            }
        });

        texRBTN.setBackground(new java.awt.Color(173, 216, 230));
        texRBTN.setText("Textile");
        texRBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texRBTNActionPerformed(evt);
            }
        });

        manRBTN.setBackground(new java.awt.Color(173, 216, 230));
        manRBTN.setText("Manufacturing");
        manRBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manRBTNActionPerformed(evt);
            }
        });

        openBTN.setText("Open");
        openBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBTNActionPerformed(evt);
            }
        });

        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });

        displayBTN.setText("Display");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });

        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        unitsLBL.setText("Units Sold");

        disLBL.setText("Distributor Cost");

        name5LBL.setText("Compostablie");

        computeBTN.setText("Compute");
        computeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeBTNActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Business Adviser App");

        jLabel2.setText("Business Type");

        imgLBL.setBackground(new java.awt.Color(173, 216, 230));
        imgLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageBusinessApp/image.png"))); // NOI18N

        esgLBL.setText("ESG Score");

        costLBL.setText("Cost Value");

        plasticLBL.setText("Plastic Removed");

        newfBTN.setText("New File");
        newfBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newfBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(121, 121, 121))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(searchBTN)
                                .addGap(18, 18, 18)
                                .addComponent(displayBTN)
                                .addGap(18, 18, 18)
                                .addComponent(addBTN)
                                .addGap(18, 18, 18)
                                .addComponent(delBTN)
                                .addGap(18, 18, 18)
                                .addComponent(computeBTN))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(name5LBL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(compTF, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(nameLBL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(revLBL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(revTF, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(unitsLBL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(unitsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(disLBL)
                                        .addGap(98, 98, 98)
                                        .addComponent(disTF, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(esgLBL)
                                .addGap(38, 38, 38)
                                .addComponent(costLBL)
                                .addGap(49, 49, 49)
                                .addComponent(plasticLBL)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manRBTN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(resRBTN)
                            .addComponent(texRBTN)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(imgLBL)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newfBTN)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(openBTN, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(saveBTN, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resRBTN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addBTN)
                        .addComponent(displayBTN)
                        .addComponent(searchBTN)
                        .addComponent(delBTN)
                        .addComponent(computeBTN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(texRBTN)
                            .addGap(6, 6, 6))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(nameLBL)
                            .addGap(5, 5, 5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manRBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(imgLBL))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(revTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(revLBL))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(unitsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(unitsLBL))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(disLBL)
                                    .addComponent(disTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(compTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name5LBL))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(costLBL)
                                    .addComponent(plasticLBL)
                                    .addComponent(esgLBL))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(openBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saveBTN)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newfBTN)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resRBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resRBTNActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().equals("Check")) {
           
           
        }
        manRBTN.setSelected(false);
        texRBTN.setSelected(false);
        
        
     
        
        unitsLBL.setText("Units Sold");
        disLBL.setText("Distrubutor Cost");
        
       
    }//GEN-LAST:event_resRBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
       
        //JOptionPane.showMessageDialog(null, resRBTN.isSelected());
        if(resRBTN.isSelected() == true){
            
            String name = nameTF.getText();
            double revenue = Double.parseDouble(revTF.getText());
            int unitsSold = Integer.parseInt(unitsTF.getText());
            double distributorCost = Double.parseDouble(disTF.getText());
            int compostable = Integer.parseInt(compTF.getText());
            Restaurant temp = new Restaurant(name, revenue, unitsSold, distributorCost, compostable);
              
            elist.add(temp);
            JOptionPane.showMessageDialog(null, "New Business added");
        }else if(manRBTN.isSelected()==true){
            String name = nameTF.getText();
            double revenue = Double.parseDouble(revTF.getText());
            int unitsSold = Integer.parseInt(unitsTF.getText());
            double machineryCost = Double.parseDouble(disTF.getText());
            int compostable = Integer.parseInt(compTF.getText());
            Manufacturing temp = new Manufacturing(name, revenue, compostable, unitsSold, machineryCost);
              
            elist.add(temp);
            JOptionPane.showMessageDialog(null, "New Business added");
        }else if(texRBTN.isSelected()==true){
            String name = nameTF.getText();
            double revenue = Double.parseDouble(revTF.getText());
            int itemsSold = Integer.parseInt(unitsTF.getText());
            double textileCost = Double.parseDouble(disTF.getText());
            double upgradeCost = Double.parseDouble(compTF.getText());
            Textile temp = new Textile(name, revenue, itemsSold, textileCost, upgradeCost);
              
            elist.add(temp);
            JOptionPane.showMessageDialog(null, "New Business added");
        }else{
            String name = nameTF.getText();
            double revenue = Double.parseDouble(revTF.getText());
            Business temp = new Business(name, revenue);
              
            elist.add(temp);
            JOptionPane.showMessageDialog(null, "New Business added");
        }
      nameTF.setText("");
      unitsTF.setText("");
      disTF.setText("");
      revTF.setText("");
      compTF.setText("");
    }//GEN-LAST:event_addBTNActionPerformed
    private void loadFile() {
      
        FileInputStream fStream;
        ObjectInputStream oStream;
        try{
            f = new File(busFile);
                    
            fStream = new FileInputStream(f);
                    
            oStream = new ObjectInputStream(fStream);
            //save the file to the arrayList
            //remind java what type of object we are getting from file
            //cast it o arrayList holding our library item obj
          
            elist=(ArrayList<Business>)oStream.readObject();
            objectTA.selectAll();
            objectTA.replaceSelection("");
            objectTA.append("sucessfully loaded data from "+busFile+ "\n");
        
            //System.out.println("file loaded    \n");
                   
            oStream.close();
        }catch(IOException | ClassNotFoundException e){
            System.out.println("error"+e +"\n");
            objectTA.append("no files to open\n");
        }
    }
    public void saveFile(){
        
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try{
            f = new File(busFile);
            fStream = new FileOutputStream(f);
            oStream = new ObjectOutputStream(fStream);
            //write to file
            oStream.writeObject(elist);
            oStream.close();
            objectTA.selectAll();
            objectTA.replaceSelection("");
            objectTA.append("sucessfully saved data to "+busFile+ "\n");
          
            //f.delete();
        }catch(IOException e){
            System.out.println("error="+e);
        }
       
    }
    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        main.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_exitBTNActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
        // TODO add your handling code here:
        String details;
        objectTA.selectAll();
        objectTA.replaceSelection("");
         for(int i = 0;i<elist.size();i++){
            Business temp;
            temp= elist.get(i);
            if(temp instanceof Restaurant){
                details= "Business: Restaurant "+" Name: "+temp.getBusinessName() +" Revenue: "+temp.getRevenue() +" units Sold: "+((Restaurant) temp).getUnitsSold()+" Distributor Cost: "+((Restaurant) temp).getDistributorCost()+" Compostable: "+((Restaurant)temp).getCompostable();
                
            }else if(temp instanceof Textile){
                details="Business: Textile "+" Name: "+temp.getBusinessName() +" Revenue: "+temp.getRevenue() +" items Sold: "+((Textile) temp).getItemsSold()+" Textile Cost: "+((Textile) temp).getTextileCost()+" Upgrade Cost: "+((Textile)temp).getUpgradeCost();
            }else if(temp instanceof Manufacturing){
                details="Business: Manufacturing "+" Name: "+temp.getBusinessName() +" Revenue: "+temp.getRevenue() +" units Sold: "+((Manufacturing) temp).getUnitsSold()+" Machinery Cost: "+((Manufacturing) temp).getMachineryCost()+" Compostable: "+((Manufacturing)temp).getCompostable();
            }else{
                details="Name: "+temp.getBusinessName() +" Revenue: "+temp.getRevenue();
            }
            objectTA.append(details+"\n");
            //JOptionPane.showMessageDialog(null,temp.printDetails());
        
        }
    }//GEN-LAST:event_displayBTNActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // TODO add your handling code here:
        objectTA.selectAll();
        objectTA.replaceSelection("");
        if(elist.isEmpty()){
            JOptionPane.showMessageDialog(null, "No one in system");
        }else{
            String searchTerm = JOptionPane.showInputDialog(null, "Enter Name");
            for(Business temp:elist){
                if(temp.getBusinessName().equalsIgnoreCase(searchTerm)){
                    objectTA.append(temp.toString()+"\n");
                }
            }
        }
    }//GEN-LAST:event_searchBTNActionPerformed

    private void delBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBTNActionPerformed
        // TODO add your handling code here:
        objectTA.selectAll();
        objectTA.replaceSelection("");
        if(elist.isEmpty()){
            JOptionPane.showMessageDialog(null, "No one in system");
        }else{
            String searchTerm = JOptionPane.showInputDialog(null, "Enter Name");
            for(int i=0; i<elist.size();i++){
                Business temp = elist.get(i);
                if(temp.getBusinessName().equalsIgnoreCase(searchTerm)){
                    elist.remove(i);
                    objectTA.append(temp.getBusinessName()+ " Removed" +"\n");
                    //JOptionPane.showMessageDialog(null,temp.getBusinessName()+ " Removed");
                }
            }
        }
        
    }//GEN-LAST:event_delBTNActionPerformed

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_nameTFActionPerformed

    private void texRBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texRBTNActionPerformed
        // TODO add your handling code here:
        
         
        manRBTN.setSelected(false);
        resRBTN.setSelected(false);
        
        unitsLBL.setText("Items Sold");
        disLBL.setText("Textile Cost");
        name5LBL.setText("Upgrade Cost");
      
    }//GEN-LAST:event_texRBTNActionPerformed

    private void manRBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manRBTNActionPerformed
        // TODO add your handling code here:
        resRBTN.setSelected(false);
        texRBTN.setSelected(false);
        
        unitsLBL.setText("Compostable Cost");
        disLBL.setText("Units Sold");
        name5LBL.setText("Machinery Cost");
   
    }//GEN-LAST:event_manRBTNActionPerformed

    private void openBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBTNActionPerformed
        // TODO add your handling code here:
        loadFile();

        /*
        for(Business l:elist){
            objectTA.append("\n"+l.toString());
        }
        */
    }//GEN-LAST:event_openBTNActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        saveFile();
    
    }//GEN-LAST:event_saveBTNActionPerformed

    private void newfBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newfBTNActionPerformed
        // TODO add your handling code here:
        count++;
        busFile= "BusList"+count+".dat";
        elist.clear();
        objectTA.selectAll();
        objectTA.replaceSelection("");
        objectTA.append("New file created "+busFile+ "\n");
        
    }//GEN-LAST:event_newfBTNActionPerformed

    private void computeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeBTNActionPerformed
        // TODO add your handling code here:
        double plastic=0, cost=0;
        int esg =0; 
        if(elist.isEmpty()){
            JOptionPane.showMessageDialog(null, "No one in system");
        }else{
            String searchTerm = JOptionPane.showInputDialog(null, "Enter Name");
        
           
                for(int i = 0;i<elist.size();i++){
                    Business temp;

                    temp= elist.get(i);
                    if(temp.getBusinessName().equalsIgnoreCase(searchTerm)){
                        if(temp instanceof Restaurant){
                            plastic=((Restaurant) temp).plasticCalc();
                            cost=temp.costCalc();
                        }else if(temp instanceof Textile){
                            plastic=((Textile) temp).plasticCalc();
                            cost=temp.costCalc();
                            esg=((Textile) temp).esgCalc();
                        }else if(temp instanceof Manufacturing){
                            cost=temp.costCalc();
                            esg=((Manufacturing) temp).esgCalc();
                            plastic=((Manufacturing) temp).plasticCalc();
                        }else{
                            cost=temp.costCalc();
                            esg=temp.esg();
                            plastic=0;
                        }
                    }
            
                }
            esgLBL.setText("ESG Score "+"\n"+Integer.toString(esg));
            plasticLBL.setText("Plastic Removed \n"+Double.toString(plastic)+"Kg");
            costLBL.setText("Cost Value \n"+Double.toString(cost)+"€");
        }
    }//GEN-LAST:event_computeBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusinessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusinessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusinessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusinessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField compTF;
    private javax.swing.JButton computeBTN;
    private javax.swing.JLabel costLBL;
    private javax.swing.JButton delBTN;
    private javax.swing.JLabel disLBL;
    private javax.swing.JTextField disTF;
    private javax.swing.JButton displayBTN;
    private javax.swing.JLabel esgLBL;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel imgLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton manRBTN;
    private javax.swing.JLabel name5LBL;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton newfBTN;
    private javax.swing.JTextArea objectTA;
    private javax.swing.JButton openBTN;
    private javax.swing.JLabel plasticLBL;
    private javax.swing.JRadioButton resRBTN;
    private javax.swing.JLabel revLBL;
    private javax.swing.JTextField revTF;
    private javax.swing.JButton saveBTN;
    private javax.swing.JButton searchBTN;
    private javax.swing.JRadioButton texRBTN;
    private javax.swing.JLabel unitsLBL;
    private javax.swing.JTextField unitsTF;
    // End of variables declaration//GEN-END:variables

   
}
